### ISSUE TITLE
适配一下腾讯云 pages

### ISSUE THREAD

**Issue by wufaziba-com** [javayhu/haitang#17]
部署了几次，一直失败![image](https://github.com/user-attachments/assets/350c843d-fd00-4080-b480-a1ca43854890)![image](https://github.com/user-attachments/assets/d572136b-5529-4be4-bc2b-c0c6c8238fe2)![image](https://github.com/user-attachments/assets/8433e483-80d2-4209-ab74-4defad397c88)![image](https://github.com/user-attachments/assets/db74d866-63eb-4fbe-9965-734182615812)![image](https://github.com/user-attachments/assets/58ba7397-c671-41b5-9525-ac619d36485f)

**Comment by javayhu** [comment]
请自行解决，没有适配腾讯云的计划
