### ISSUE TITLE
错误：giscus is not installed on this repository

### ISSUE THREAD

**Issue by xv44586** [javayhu/haitang#4]
网页评论区出现如下错误：
错误：giscus is not installed on this repository

giscus 未安装成功大概

**Comment by javayhu** [comment]
自己部署的话可以看下 Giscus.astro 文件，替换成自己创建的 Giscus  App 的参数就可以。

https://github.com/javayhu/haitang/blob/main/src/components/Giscus.astro

btw，如果是直接使用开源项目版本的话，配置的参数是当前项目的discussion#Comments，所以理论上不会有这个问题。

<img width="1244" alt="SCR-20240706-tpvm" src="https://github.com/javayhu/haitang/assets/1982582/9cd1a374-8848-4cca-b63e-0f202de01939">
